### ISSUE TITLE
packaging builders make long folder names regardless of package

### ISSUE THREAD

**Issue by endrift** [mgba-emu/mgba-infrastructure#1]
The packaging builders always include the commit hash and a bunch of other things in the folder name in the package, regardless of the intent of the packaging. This is detrimental for release packages.

This issue replaces https://github.com/mgba-emu/mgba/issues/26.

**Comment by endrift** [comment]
I think this is fixed for upcoming releases. Will check with 0.3.2/0.4.0, whichever actually happens.

**Comment by karasuhebi** [comment]
Yay! ^_^
