### ISSUE TITLE
Include build numbers in the archive and folder names for nightly builds

### ISSUE THREAD

**Issue by karasuhebi** [mgba-emu/mgba-infrastructure#3]
Currently the packaging builders include the commit hash on nightly packages. It would be nice for them to also include the build number that's listed on mGBA's titlebar.

As it stands right now, when you download a nightly, the archive and folder name read **mGBA-nightly-2017-01-02-win32-180418a74f035dfd8b7bddb2a437b9ed9b528d3a** while the titlebar on mGBA itself reads **mGBA - 0.6-4261-180418a**.

Including build numbers would be useful since sometimes users refers to builds using this number (see [issue #201](https://github.com/mgba-emu/mgba/issues/201) for an example) and it would make downloading the correct build from the [nightlies archive](https://mgba.io/nightlies.html) much easier.

**Comment by endrift** [comment]
This did get fixed at some point.

**Comment by karasuhebi** [comment]
Nice, thanks for the update. :D
